extern zend_class_entry *QAbstractButton_ce_ptr;
void 	_register_QAbstractButton();
extern zend_class_entry *QAbstractSlider_ce_ptr;
void 	_register_QAbstractSlider();
extern zend_class_entry *QActionEvent_ce_ptr;
void 	_register_QActionEvent();
extern zend_class_entry *QApplication_ce_ptr;
void 	_register_QApplication();
extern zend_class_entry *QBoxLayout_ce_ptr;
void 	_register_QBoxLayout();
extern zend_class_entry *QChar_ce_ptr;
void 	_register_QChar();
extern zend_class_entry *QCharRef_ce_ptr;
void 	_register_QCharRef();
extern zend_class_entry *QClipboardEvent_ce_ptr;
void 	_register_QClipboardEvent();
extern zend_class_entry *QCloseEvent_ce_ptr;
void 	_register_QCloseEvent();
extern zend_class_entry *QContextMenuEvent_ce_ptr;
void 	_register_QContextMenuEvent();
extern zend_class_entry *QCoreApplication_ce_ptr;
void 	_register_QCoreApplication();
extern zend_class_entry *QDate_ce_ptr;
void 	_register_QDate();
extern zend_class_entry *QDateTime_ce_ptr;
void 	_register_QDateTime();
extern zend_class_entry *QDragEnterEvent_ce_ptr;
void 	_register_QDragEnterEvent();
extern zend_class_entry *QDragLeaveEvent_ce_ptr;
void 	_register_QDragLeaveEvent();
extern zend_class_entry *QDragMoveEvent_ce_ptr;
void 	_register_QDragMoveEvent();
extern zend_class_entry *QDragResponseEvent_ce_ptr;
void 	_register_QDragResponseEvent();
extern zend_class_entry *QDropEvent_ce_ptr;
void 	_register_QDropEvent();
extern zend_class_entry *QFileOpenEvent_ce_ptr;
void 	_register_QFileOpenEvent();
extern zend_class_entry *QFocusEvent_ce_ptr;
void 	_register_QFocusEvent();
extern zend_class_entry *QFont_ce_ptr;
void 	_register_QFont();
extern zend_class_entry *QFrame_ce_ptr;
void 	_register_QFrame();
extern zend_class_entry *QGridLayout_ce_ptr;
void 	_register_QGridLayout();
extern zend_class_entry *QHBoxLayout_ce_ptr;
void 	_register_QHBoxLayout();
extern zend_class_entry *QHelpEvent_ce_ptr;
void 	_register_QHelpEvent();
extern zend_class_entry *QHideEvent_ce_ptr;
void 	_register_QHideEvent();
extern zend_class_entry *QHoverEvent_ce_ptr;
void 	_register_QHoverEvent();
extern zend_class_entry *QIconDragEvent_ce_ptr;
void 	_register_QIconDragEvent();
extern zend_class_entry *QInputEvent_ce_ptr;
void 	_register_QInputEvent();
extern zend_class_entry *QInputMethodEvent_ce_ptr;
void 	_register_QInputMethodEvent();
extern zend_class_entry *Attribute_ce_ptr;
void 	_register_Attribute();
extern zend_class_entry *QKeyEvent_ce_ptr;
void 	_register_QKeyEvent();
extern zend_class_entry *QLCDNumber_ce_ptr;
void 	_register_QLCDNumber();
extern zend_class_entry *QLabel_ce_ptr;
void 	_register_QLabel();
extern zend_class_entry *QLatin1Char_ce_ptr;
void 	_register_QLatin1Char();
extern zend_class_entry *QLatin1String_ce_ptr;
void 	_register_QLatin1String();
extern zend_class_entry *QLayout_ce_ptr;
void 	_register_QLayout();
extern zend_class_entry *QLayoutItem_ce_ptr;
void 	_register_QLayoutItem();
extern zend_class_entry *QLineEdit_ce_ptr;
void 	_register_QLineEdit();
extern zend_class_entry *QMouseEvent_ce_ptr;
void 	_register_QMouseEvent();
extern zend_class_entry *QMoveEvent_ce_ptr;
void 	_register_QMoveEvent();
extern zend_class_entry *QObject_ce_ptr;
void 	_register_QObject();
extern zend_class_entry *QObjectData_ce_ptr;
void 	_register_QObjectData();
extern zend_class_entry *QObjectUserData_ce_ptr;
void 	_register_QObjectUserData();
extern zend_class_entry *QPaintEvent_ce_ptr;
void 	_register_QPaintEvent();
extern zend_class_entry *QPainter_ce_ptr;
void 	_register_QPainter();
extern zend_class_entry *QPushButton_ce_ptr;
void 	_register_QPushButton();
extern zend_class_entry *QResizeEvent_ce_ptr;
void 	_register_QResizeEvent();
extern zend_class_entry *QShortcutEvent_ce_ptr;
void 	_register_QShortcutEvent();
extern zend_class_entry *QShowEvent_ce_ptr;
void 	_register_QShowEvent();
extern zend_class_entry *QSlider_ce_ptr;
void 	_register_QSlider();
extern zend_class_entry *QSpacerItem_ce_ptr;
void 	_register_QSpacerItem();
extern zend_class_entry *QStatusTipEvent_ce_ptr;
void 	_register_QStatusTipEvent();
extern zend_class_entry *QString_ce_ptr;
void 	_register_QString();
extern zend_class_entry *QTabletEvent_ce_ptr;
void 	_register_QTabletEvent();
extern zend_class_entry *QTime_ce_ptr;
void 	_register_QTime();
extern zend_class_entry *QTimer_ce_ptr;
void 	_register_QTimer();
extern zend_class_entry *QToolBarChangeEvent_ce_ptr;
void 	_register_QToolBarChangeEvent();
extern zend_class_entry *QVBoxLayout_ce_ptr;
void 	_register_QVBoxLayout();
extern zend_class_entry *QWhatsThisClickedEvent_ce_ptr;
void 	_register_QWhatsThisClickedEvent();
extern zend_class_entry *QWheelEvent_ce_ptr;
void 	_register_QWheelEvent();
extern zend_class_entry *QWidget_ce_ptr;
void 	_register_QWidget();
extern zend_class_entry *QWidgetData_ce_ptr;
void 	_register_QWidgetData();
extern zend_class_entry *QWidgetItem_ce_ptr;
void 	_register_QWidgetItem();
extern zend_class_entry *QWindowStateChangeEvent_ce_ptr;
void 	_register_QWindowStateChangeEvent();
