/*
 * PHP-Qt - The PHP language bindings for Qt
 *
 * Copyright (C) 2005
 * Thomas Moenicke <tm@ippfp.org>,
 * Jean-Luc Gyger <jean_luc.gyger@freesurf.ch>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * QHelpEvent.cpp - QHelpEvent PHP implementation.
 * begin           : Wed Jan  4 01:19:22 2006
 * generated by    : moni using kalyptus 0.9.
 */

#include <iostream>
using namespace std;

#include "../php_qt.h"

#include <QHelpEvent>



/*********************************
 *    class     QHelpEvent
 *    function  x
 *    flags:    c
 *
 *    @param   -

 *    @access   public
 *    @return   int
*********************************/
ZEND_METHOD(QHelpEvent, x){
	if (ZEND_NUM_ARGS() == 0){
		QHelpEvent *o = (QHelpEvent*) PHP_QT_FETCH();
		RETURN_LONG(o->x());
	}
}


/*********************************
 *    class     QHelpEvent
 *    function  y
 *    flags:    c
 *
 *    @param   -

 *    @access   public
 *    @return   int
*********************************/
ZEND_METHOD(QHelpEvent, y){
	if (ZEND_NUM_ARGS() == 0){
		QHelpEvent *o = (QHelpEvent*) PHP_QT_FETCH();
		RETURN_LONG(o->y());
	}
}


/*********************************
 *    class     QHelpEvent
 *    function  globalX
 *    flags:    c
 *
 *    @param   -

 *    @access   public
 *    @return   int
*********************************/
ZEND_METHOD(QHelpEvent, globalX){
	if (ZEND_NUM_ARGS() == 0){
		QHelpEvent *o = (QHelpEvent*) PHP_QT_FETCH();
		RETURN_LONG(o->globalX());
	}
}


/*********************************
 *    class     QHelpEvent
 *    function  globalY
 *    flags:    c
 *
 *    @param   -

 *    @access   public
 *    @return   int
*********************************/
ZEND_METHOD(QHelpEvent, globalY){
	if (ZEND_NUM_ARGS() == 0){
		QHelpEvent *o = (QHelpEvent*) PHP_QT_FETCH();
		RETURN_LONG(o->globalY());
	}
}


/*********************************
 *    class     QHelpEvent
 *    function  pos
 *    flags:    c
 *
 *    @param   -

 *    @access   public
 *    @return   const QPoint&
*********************************/
ZEND_METHOD(QHelpEvent, pos){
	if (ZEND_NUM_ARGS() == 0){
		QHelpEvent *o = (QHelpEvent*) PHP_QT_FETCH();
		const QPoint& obj = (const QPoint&) o->pos();
		zend_class_entry *ce;                                   
		    object_init_ex(return_value, QHelpEvent_ce_ptr);     
		    zend_rsrc_list_entry le;                            
		    le.ptr = &obj;                                       
		    php_qt_register(return_value,le);                   
		    return;                                             
	}
}


/*********************************
 *    class     QHelpEvent
 *    function  globalPos
 *    flags:    c
 *
 *    @param   -

 *    @access   public
 *    @return   const QPoint&
*********************************/
ZEND_METHOD(QHelpEvent, globalPos){
	if (ZEND_NUM_ARGS() == 0){
		QHelpEvent *o = (QHelpEvent*) PHP_QT_FETCH();
		const QPoint& obj = (const QPoint&) o->globalPos();
		zend_class_entry *ce;                                   
		    object_init_ex(return_value, QHelpEvent_ce_ptr);     
		    zend_rsrc_list_entry le;                            
		    le.ptr = &obj;                                       
		    php_qt_register(return_value,le);                   
		    return;                                             

	}
}


ZEND_METHOD(QHelpEvent,__construct){

	QHelpEvent *QHelpEvent_ptr = new QHelpEvent();

	if(ZEND_NUM_ARGS() == 3){
		zval* param_0;
		zval* param_1;
		zval* param_2;
		if(zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC,"zzz", &param_1, &param_2, &param_3) == FAILURE) {
			return;
		}
		 /*long type Type*/
		if(Z_TYPE_P(param_0) == IS_LONG) {
			Type tmp(Z_STRVAL_P(param_0));
			QHelpEvent_ptr = new QHelpEvent(tmp);
		}
		 /*long pos QPoint&*/
		if(Z_TYPE_P(param_1) == IS_LONG) {
			QPoint& tmp(Z_STRVAL_P(param_1));
			QHelpEvent_ptr = new QHelpEvent(tmp);
		}
		 /*long globalPos QPoint&*/
		if(Z_TYPE_P(param_2) == IS_LONG) {
			QPoint& tmp(Z_STRVAL_P(param_2));
			QHelpEvent_ptr = new QHelpEvent(tmp);
		}
	}

	PHP_QT_REGISTER(QHelpEvent_ptr);
	RETURN_NULL();
}

PHP_QT_DESTRUCT(QHelpEvent);

