/*
 * PHP-Qt - The PHP language bindings for Qt
 *
 * Copyright (C) 2006
 * Thomas Moenicke <tm@ippfp.org>,
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * QHideEvent.cpp - QHideEvent PHP implementation.
 * begin           : Tue Jun  6 22:42:56 2006
 * generated by    : moni using kalyptus 0.9.
 */

#include <iostream>
using namespace std;

#include "../php_qt.h"


#include <QHideEvent>
/// DEBUG:destructor skipped.
#include <QMetaMethod>
class QHideEvent_php_qt:public QHideEvent
{

public:
  QHideEvent_php_qt(zval * zend_ptr);


  zval *zend_ptr;
};

QHideEvent_php_qt::QHideEvent_php_qt(zval * zend_ptr):QHideEvent()
{
  this->zend_ptr = zend_ptr;
}

/*!
 * method QHideEvent
 * 
 * @param: -
 * @param: -
 * 
 * @access	public
 * @return	
 * @flags	
 */

ZEND_METHOD(QHideEvent, __construct)
{
  ///
  if (ZEND_NUM_ARGS() == 0) {
    PHP_QT_FETCH_0_ARGS();
    if (1) {
      if (getThis() == NULL) {
        php_error(E_ERROR, "method '__construct' is not static");
        RETURN_NULL();
      }
      /// try 
      QHideEvent_php_qt *
        selfpointer = new QHideEvent_php_qt(getThis());

      PHP_QT_REGISTER(selfpointer);
      RETURN_NULL();
    }
  }
  php_error(E_ERROR, "could not parse argument in QHideEvent::QHideEvent(...) ");
}
