php_qt.lo: /home/moni/software/php-5.1.0RC1/ext/php_qt/php_qt.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/moni/software/php-5.1.0RC1/ext/php_qt $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/moni/software/php-5.1.0RC1/ext/php_qt/php_qt.c -o php_qt.lo 
$(phplibdir)/php_qt.la: ./php_qt.la
	$(LIBTOOL) --mode=install cp ./php_qt.la $(phplibdir)

./php_qt.la: $(shared_objects_php_qt) $(PHP_QT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_php_qt) $(PHP_QT_SHARED_LIBADD)

